# -*- coding: utf-8 -*-
"""Project 93.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W-PebbAsWRDqCwYGPaT3gX6cfAULSI3z
"""

import random

number =  random.randrange(1, 10)
chances = 5
Gtype = "lost"

while chances >= 1:

  g = int (input("gues a number "))
  if g < number :
    print("nah, its greater than " + str(g))
    chances = chances - 1
    print("You have "+ str(chances) + " chance(s) left")

  elif g > number:
    print("its lower than " + str(g))  
    chances = chances - 1
    print("You have "+ str(chances) + " chance(s) left")
    
  else:
    print("that right")
    print("")
    Gtype = "won"
    chances = 0    

if chances < 1 and Gtype == "lost":
  print("u lose")
elif chances < 14
 and Gtype == "won":
  print("u win")

4
4